import { config } from 'dotenv'

config()

const {
    AWS_REGION = '',
    ENVIRONMENT = '',
    DYNAMO_DB_URI = '',
    AUTH0_API_IDENTIFIER = '',
    AUTH0_DOMAIN = '',
    AUTH0_CLIENT_ID = '',
    AUTH0_CLIENT_SECRET = '',
    LOCAL_JWT_SECRET = '',
    LOGGER_DISABLE_CONSOLE_INTERCEPT = false,
    KEYS_CHECK_PERIOD_IN_SECONDS = 120,
    AWS_DEFAULT_REGION = 'eu-west-1',
    AWS_USE_SQS_LOCAL = false,
    SQS_LOCAL_ENDPOINT = 'http://localhost:9324',
    SQS_RECEIVE_WAIT_TIME_SECONDS = 20,
    SQS_DEV_SUBSCRIBE_ENDPOINT = 'http://localhost:5555',
    JOB_QUEUE_NAME = 'jobQueue',
} = process.env

export {
    AUTH0_DOMAIN,
    AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET,
    LOCAL_JWT_SECRET,
    AWS_REGION,
    ENVIRONMENT,
    DYNAMO_DB_URI,
    LOGGER_DISABLE_CONSOLE_INTERCEPT,
    AUTH0_API_IDENTIFIER,
    KEYS_CHECK_PERIOD_IN_SECONDS,
    AWS_DEFAULT_REGION,
    AWS_USE_SQS_LOCAL,
    SQS_LOCAL_ENDPOINT,
    SQS_RECEIVE_WAIT_TIME_SECONDS,
    SQS_DEV_SUBSCRIBE_ENDPOINT,
    JOB_QUEUE_NAME,
}
